version: '3.3'

services:
  db:
    image: postgres
    restart: always
    container_name: digest_db
    hostname: db
    ports:
      - 5432:5432
    networks:
      - digest_net
    volumes:
      - digest_db_volume_dev:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=digest
      - POSTGRES_USER=digester
      - POSTGRES_PASSWORD=C9FbrA7Mt4asx3aP
    command:
      - "postgres"
      - "-c"
      - "max_connections=10000"
      - "-c"
      - "shared_buffers=2GB"

networks:
  digest_net:

volumes:
  digest_db_volume_dev: