version: '3.3'
services:
  web:
    image: ghcr.io/bionetslab/digest-web:main
    container_name: digest-frontend
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    ports:
      - "8071:80"
    restart: always
  digest_backend:
    image: ghcr.io/bionetslab/digest-api:main
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    container_name: digest_backend
    env_file:
      - './docker-django.env'
    restart: always
    volumes:
      - digest_volume:/usr/src/digest/mapping_files
    command:
      - "sh"
      - "/usr/src/digest/docker-entrypoint.sh"
    ports:
      - 8072:8000
    networks:
      - digest_net
    depends_on:
      - digest_db
      - digest_redis
  digest_redis:
    image: redis
    restart: always
    command: [ "redis-server" ]
    container_name: digest_redis
    hostname: digest_redis
    networks:
      - digest_net
    depends_on:
      - digest_db
  digest_celery:
    command:
      - "sh"
      - "/usr/src/digest/scripts/start_celery_worker.sh"
    restart: always
    image: ghcr.io/bionetslab/digest-api:main
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    container_name: digest_celery
    hostname: digest_celery
    env_file:
      - './docker-django.env'
    volumes:
      - digest_volume:/usr/src/digest/mapping_files
    depends_on:
      - digest_redis
      - digest_db
    networks:
      - digest_net
  digest_celery-beat:
    command:
      - "sh"
      - "/usr/src/digest/scripts/start_celery_beat.sh"
    build: .
    container_name: digest_celery_beat
    hostname: digest_celery_beat
    env_file:
      - './docker-django.env'
    volumes:
      - ./:/usr/src/digest/
    depends_on:
      - digest_redis
      - digest_db
    networks:
      - digest_net
  digest_db:
    image: postgres:15
    restart: always
    container_name: digest_db
    hostname: digest_db
#    ports:
#      - 5432:5432
    networks:
      - digest_net
    volumes:
      - digest_db_volume:/var/lib/postgresql/example_files
    environment:
      - POSTGRES_DB=digest
      - POSTGRES_USER=digester
      - POSTGRES_PASSWORD=C9FbrA7Mt4asx3aP
    command:
      - "postgres"
      - "-c"
      - "max_connections=10000"
      - "-c"
      - "shared_buffers=2GB"

networks:
  digest_net:

volumes:
  digest_volume:
  digest_db_volume:
